{
 "title": "SMART CITY DASHBOARD1",
 "time": { "from": "2023-11-27T02:26:47.556Z", "to": "2023-11-27T02:27:35.600Z" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color:teal; text-align:center; padding:10px;\">\n  <h1 style=\"color:white; font-weight:bold;\">SMART CITY IOT DASHBOARD</h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "<div style=\"background-color:grey; text-align:center; padding:3px;\">\n  <h3 style=\"color:black; font-weight:bold;\">Smart City Index Analysis</h1>\n</div>"
   }
  },
  {
   "title": "Country-wise",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"smartcity_index\") from data group by \"country\", time(2h)\n"
    }
   ]
  },
  {
   "title": "City-wise",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"smartcity_index\") from data group by \"city\", time(2h)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select max(\"smartcity_index\"), \"country\" from data \n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select max(\"smartcity_index\"), \"country\" from data \n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select min(\"smartcity_index\"), \"country\" from data \n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select min(\"smartcity_index\"), \"country\" from data \n"
    }
   ]
  },
  {
   "title": "IOT Indexes for Canada",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "SELECT \"smart_people\", \"smart_government\", \"smart_living\", \"smart_mobility\", \"smart_environment\", \"smart_economy\" FROM \"data\" where (\"country\" = 'Canada')"
    }
   ]
  },
  {
   "title": "IOT Indexes for China",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "query": "SELECT \"smart_people\", \"smart_government\", \"smart_living\", \"smart_mobility\", \"smart_environment\", \"smart_economy\" FROM \"data\" where (\"country\" = 'China')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"background-color:grey; text-align:center; padding:3px;\">\n  <h3 style=\"color:black; font-weight:bold;\">IOT Indexes</h1>\n</div>"
   }
  },
  {
   "title": "Economy Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 1, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_economy\") as avgeconomy into economy_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avgeconomy\") from economy_data"
    },
    {
     "query": "select \"country\", min(\"avgeconomy\") from economy_data"
    }
   ]
  },
  {
   "title": "Living Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_living\") as avgliving into living_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avgliving\") from living_data"
    },
    {
     "query": "select \"country\", min(\"avgliving\") from living_data"
    }
   ]
  },
  {
   "title": "Government Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_government\") as avggovernment into government_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avggovernment\") from government_data"
    },
    {
     "query": "select \"country\", min(\"avggovernment\") from government_data"
    }
   ]
  },
  {
   "title": "Environment Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 1, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_environment\") as avgenvironment into environment_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avgenvironment\") from environment_data"
    },
    {
     "query": "select \"country\", min(\"avgenvironment\") from environment_data"
    }
   ]
  },
  {
   "title": "Mobility Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_mobility\") as avgmobility into mobility_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avgmobility\") from mobility_data"
    },
    {
     "query": "select \"country\", min(\"avgmobility\") from mobility_data"
    }
   ]
  },
  {
   "title": "People Index",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "select mean(\"smart_people\") as avgpeople into people_data from data where time > now() - 2m group by \"country\""
    },
    {
     "query": "select \"country\", max(\"avgpeople\") from people_data"
    },
    {
     "query": "select \"country\", min(\"avgpeople\") from people_data"
    }
   ]
  }
 ]
}